### ISSUE TITLE
selfies_dict中少了一部分结构

### ISSUE THREAD

**Issue by Chalorate** [QizhiPei/BioT5#13]
当我尝试在新的SELFIES数据集上应用模型时，发现selfies_dict中缺少结构”[-/Ring1]“，导致该结构被编码为[784,    18,    87,   448,    53,  536,   908,]，解码时有出现”[[”的情况。
请问是有意删除该结构，还是因为预训练的数据集中没有包含该结构呢？
如果是有意删除，请问是出于什么原因删除的呢？

**Comment by QizhiPei** [comment]
你好。由于SELFIES本身没有封闭的词表，所以我们从预训练和常见的下游任务中采样数据来构建BioT5的SELFIES词表。这个是因为用来构建词表的数据集中都没有包含该结构。

**Comment by Chalorate** [comment]
好的，感谢您的回复。也感谢您所作的工作~
