### ISSUE TITLE
Text-To-Protein Generation Recommended Model

### ISSUE THREAD

**Issue by amelie-iska** [QizhiPei/BioT5#8]
Hi again! I was just wondering which checkpoint is recommended for text-to-protein generation.

**Comment by QizhiPei** [comment]
Hi,
For BioT5, there is no available checkpoint to directly do text-to-protein generation. You can try to finetune BioT5 on this type of dataset.
You can also try another model like Mol-Instructions protein-oriented model (https://huggingface.co/zjunlp/llama-molinst-protein-7b).
